# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 20, 53, 40, 848079, tzinfo=utc)),
        ),
    ]
