# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playmaster', '0002_auto_20170504_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
