# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaster', '0004_auto_20170504_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
